FROM openjdk:17-jdk-slim AS builder

WORKDIR /app

COPY . .

RUN chmod +x gradlew

RUN ./gradlew clean :app:client-app:build -x test

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=builder /app/app/client-app/build/libs/*.jar app.jar
# 스크립트를 이미지에 복사
COPY entrypoint.sh /app/entrypoint.sh


EXPOSE 8081

ENV SPRING_PROFILES_ACTIVE=deploy

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]